server:
  port: 8888

spring:
  application:
    name: didactic-config-server

  eureka:
    instance:
      hostname: didactic-config-server
      prefer-ip-address: false

    client:
      register-with-eureka: true
      fetch-registry: true
      healthcheck:
        enabled: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

  cloud:
    config:
      server:
        git:
          uri: https://github.com/dorucrivoi/didactic-config-repo
          default-label: main
          clone-on-start: true
          search-paths: catalogue,didactic-personal
